#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: senha
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#  h2:
#    console.path: "/h2"
#    console.enabled: true